export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-primary-container": "#87a0cd",
          "on-secondary-container": "#596674",
          "on-secondary-fixed-variant": "#3b4856",
          "inverse-on-surface": "#f0f1f2",
          "outline-variant": "#c4c6cf",
          "on-primary": "#ffffff",
          "secondary-fixed": "#d6e4f5",
          "surface-dim": "#d9dadb",
          "on-surface": "#191c1d",
          "on-primary-fixed": "#001b3d",
          "on-error-container": "#93000a",
          "outline": "#74777f",
          "background": "#f8f9fa",
          "on-secondary": "#ffffff",
          "surface-container-low": "#f3f4f5",
          "secondary": "#53606e",
          "surface-container-highest": "#e1e3e4",
          "tertiary": "#3d1400",
          "surface-container-high": "#e7e8e9",
          "on-tertiary-fixed-variant": "#7a3000",
          "primary-fixed-dim": "#aec7f7",
          "surface-tint": "#465f88",
          "tertiary-fixed": "#ffdbcc",
          "on-error": "#ffffff",
          "surface-variant": "#e1e3e4",
          "surface-container-lowest": "#ffffff",
          "tertiary-fixed-dim": "#ffb693",
          "secondary-container": "#d6e4f5",
          "on-surface-variant": "#44474e",
          "surface": "#f8f9fa",
          "inverse-surface": "#2e3132",
          "primary-container": "#1b365d",
          "error-container": "#ffdad6",
          "surface-container": "#edeeef",
          "on-secondary-fixed": "#101d29",
          "tertiary-container": "#5f2300",
          "on-background": "#191c1d",
          "primary": "#002046",
          "on-primary-fixed-variant": "#2e476f",
          "error": "#ba1a1a",
          "primary-fixed": "#d6e3ff",
          "on-tertiary": "#ffffff",
          "on-tertiary-container": "#ff7627",
          "inverse-primary": "#aec7f7",
          "secondary-fixed-dim": "#bac8d8",
          "surface-bright": "#f8f9fa",
          "on-tertiary-fixed": "#351000"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "fontFamily": {
          "headline": ["Manrope"],
          "body": ["Inter"],
          "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
